steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/helloworld:latest",
        ".",
      ]
  # Deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      [
        "run",
        "--filename=kubernetes/node-kubernetes/node.yaml",
        "--location=$LOCATION",
        "--cluster=node-kubernetes-349713-gke"
      ]
substitutions:
  _REGISTRY_URL: "us-central1-docker.pkg.dev"
  _REGISTRY: "node-kubernetes"
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/helloworld:latest"
