apiVersion: v1
kind: Service
metadata:
  name: node-kubernetes
spec:
  selector:
    app: node-kubernetes
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-kubernetes
  template:
    metadata:
      labels:
        app: node-kubernetes
    spec:
      containers:
      - name: node-kubernetes
        image: us-central1-docker.pkg.dev/node-kubernetes-349713/node-kubernetes/helloworld:latest
        ports:
          - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "development"
